image: gitlab-registry.cern.ch/linuxsupport/cs9-base
variables:
  JSONNET_VERSION: "v0.18.0"
  GRIZZLY_VERSION: "v0.2.0-beta3"
before_script:
  - yum install -y go curl
  - export PATH="$HOME/go/bin:$PATH"
  - go install github.com/google/go-jsonnet/cmd/jsonnet@${JSONNET_VERSION}
  - go install github.com/google/go-jsonnet/cmd/jsonnetfmt@${JSONNET_VERSION}
    #- curl -fSL -o "/usr/local/bin/grr" "https://github.com/grafana/grizzly/releases/download/${GRIZZLY_VERSION}/grr-linux-amd64"
  - curl -fSL -o "/usr/local/bin/grr" "https://github.com/MrFreezeex/grizzly/releases/download/dev/grr"
  - chmod +x "/usr/local/bin/grr"

.qa_grafana:
  variables:
    GRAFANA_URL: $GRAFANA_QA_URL
.prod_grafana:
  variables:
    GRAFANA_URL: $GRAFANA_PROD_URL

install-deps:
  stage: .pre
  variables:
    JB_VERSION: "v0.4.0"
  before_script:
  script:
    - go install github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb@${JB_VERSION}
    - jb install
  artifacts:
    paths:
      - vendor/
    expire_in: 1 month

lint:
  stage: test
  script:
    - jsonnetfmt --test $(find . -name '*.jsonnet' -o -name '*.libsonnet')

diff:
  extends: .prod_grafana
  stage: test
  script:
    - grr diff grr.jsonnet -t 'Dashboard*' > dashboards-diff.txt
  artifacts:
    expose_as: 'Dashboards diff'
    paths:
      - dashboards-diff.txt

deploy-dashboards-qa:
  extends: .qa_grafana
  stage: deploy
  script:
    - echo "${GRAFANA_URL}"
    - grr apply grr.jsonnet -t 'Dashboard*'

deploy-dashboards:
  extends: .prod_grafana
  allow_failure: true
  stage: deploy
  script:
    - grr apply grr.jsonnet -t 'Dashboard*'
  only:
    refs:
      - main
      - tags
